---

- name: install base packages
  apt: name={{item}} state=installed install_recommends=no
  with_items:
    - wget
    - iptables
    - iptables-persistent
    - conntrack
    - ntp

- name: latest bash (CVE-2014-6271)
  apt: name=bash state=latest install_recommends=no

- name: remove timezone
  command: rm -f arg1 removes=/etc/localtime

- name: set timezone to UTC
  command: ln -s /usr/share/zoneinfo/UTC arg1 creates=/etc/localtime

- name: setting hostname
  copy: content="akanda-linux" dest=/etc/hostname

- name: set default nameserver
  copy: content="nameserver 8.8.8.8" dest=/etc/resolv.conf

- name: vanity motd
  template: src=motd.j2 dest=/etc/motd

- name: disable fsck on boot via fastboot
  file: path=/fastboot state=touch

