---
- name: install dnsmasq (Debian)
  apt: name=dnsmasq state=installed install_recommends=no

- name: Create config directory
  file: path={{dnsmasq_conf_dir}} state=directory mode=0755

- name: Generate Config
  template: src=dnsmasq.conf.j2 dest={{dnsmasq_conf_file}}

- name: Ensure dnsmasq is started
  service: name=dnsmasq state=started enabled=yes

